services:
  db:
    image: postgres:13
    container_name: olist_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d olist_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: olist_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.kaggle:/root/.kaggle  # Mount kaggle API token
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/olist_db"
      PYTHONPATH: "."

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: olist_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"

volumes:
  postgres_data:
